import React, { useState } from 'react';
import { useStudents } from '../context/StudentContext';
import { useAuth } from '../context/AuthContext';
import { useNotification } from '../context/NotificationContext';
import { 
  FileText, 
  Download, 
  Printer, 
  Calendar, 
  FileSpreadsheet, 
  Eye,
  ShieldCheck
} from 'lucide-react';
import { Breadcrumbs } from '../components/Breadcrumbs';

interface ReportsPageProps {
  onNavigate: (page: string) => void;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ onNavigate }) => {
  const { students } = useStudents();
  const { teacher } = useAuth();
  const { showToast } = useNotification();

  const [reportType, setReportType] = useState<'RISK_SUMMARY' | 'ATTENDANCE_VULNERABILITY' | 'ACADEMIC_DECLINE' | 'FULL_COHORT'>('RISK_SUMMARY');
  const [dateRange, setDateRange] = useState('CURRENT_TERM');
  const [selectedCohort, setSelectedCohort] = useState('ALL');
  const [showPreviewModal, setShowPreviewModal] = useState(false);

  const handleDownloadReport = () => {
    // Generate formatted text/csv export
    const content = `EARLYFLAG ACADEMIC RISK REPORT
Generated By: ${teacher?.name} (${teacher?.id})
Department: ${teacher?.department}
Report Type: ${reportType}
Date: ${new Date().toLocaleDateString()}
Cohort: ${selectedCohort}
--------------------------------------------------
Total Students: ${students.length}
High Risk Flagged: ${students.filter(s => s.riskLevel === 'HIGH').length}
Medium Risk Flagged: ${students.filter(s => s.riskLevel === 'MEDIUM').length}
Low Risk (Stable): ${students.filter(s => s.riskLevel === 'LOW').length}

STUDENT DETAILS:
${students.map(s => `[${s.studentId}] ${s.name} | Class ${s.class}-${s.section} | Score: ${s.riskScore}/100 (${s.riskLevel}) | Reasons: ${s.reasonCodes.join(', ') || 'None'}`).join('\n')}
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `EarlyFlag_${reportType}_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    showToast({ type: 'success', title: 'Report Downloaded', message: 'Report generated and saved to your device.' });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="page-content animate-fade">
      <Breadcrumbs
        items={[
          { label: 'Dashboard', onClick: () => onNavigate('dashboard') },
          { label: 'Academic Risk Reports', active: true }
        ]}
      />

      {/* Header */}
      <div style={{ marginBottom: '1.75rem' }}>
        <h1 style={{ fontSize: '1.65rem', fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>
          Reports & Export Center
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', marginTop: '0.2rem' }}>
          Generate official institutional risk summaries, intervention histories, and attendance warnings.
        </p>
      </div>

      {/* Report Config Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.5rem', marginBottom: '2rem' }}>
        {/* Left: Configuration Form */}
        <div className="ef-card">
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '1.25rem', color: 'var(--text-primary)' }}>
            Configure Report Parameters
          </h3>

          {/* Report Type Selector */}
          <div className="form-group">
            <label className="form-label">Select Report Type</label>
            <select
              className="form-select"
              value={reportType}
              onChange={(e) => setReportType(e.target.value as any)}
            >
              <option value="RISK_SUMMARY">Student Risk Summary & Trigger Log</option>
              <option value="ATTENDANCE_VULNERABILITY">Attendance Trajectory & Absence Warnings</option>
              <option value="ACADEMIC_DECLINE">Term-over-Term Academic Decline Audit</option>
              <option value="FULL_COHORT">Comprehensive Multi-Signal Roster</option>
            </select>
          </div>

          {/* Date Range */}
          <div className="form-group">
            <label className="form-label">Evaluation Window</label>
            <select
              className="form-select"
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
            >
              <option value="CURRENT_TERM">Current Evaluation Window (28 Days)</option>
              <option value="TERM_2">Full Term 2 (2026–27)</option>
              <option value="FULL_YEAR">Academic Year 2026–27 to date</option>
            </select>
          </div>

          {/* Cohort Selector */}
          <div className="form-group">
            <label className="form-label">Cohort / Class Section</label>
            <select
              className="form-select"
              value={selectedCohort}
              onChange={(e) => setSelectedCohort(e.target.value)}
            >
              <option value="ALL">All Assigned Classes (10-A, 10-B, 9-A, 9-B)</option>
              <option value="10-A">Class 10 - Section A</option>
              <option value="10-B">Class 10 - Section B</option>
              <option value="9-A">Class 9 - Section A</option>
              <option value="9-B">Class 9 - Section B</option>
            </select>
          </div>

          <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem', borderTop: '1px solid var(--border-subtle)', paddingTop: '1rem' }}>
            <button className="btn btn-secondary btn-sm" onClick={() => setShowPreviewModal(true)} style={{ gap: '0.4rem', flex: 1 }}>
              <Eye size={14} />
              <span>Preview Report</span>
            </button>
            <button className="btn btn-primary btn-sm" onClick={handleDownloadReport} style={{ gap: '0.4rem', flex: 1 }}>
              <Download size={14} />
              <span>Export Report</span>
            </button>
          </div>
        </div>

        {/* Right: Available Report Templates */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div
            className="ef-card"
            style={{
              cursor: 'pointer',
              borderColor: reportType === 'RISK_SUMMARY' ? 'var(--brand-primary-light)' : 'var(--border-subtle)',
              background: reportType === 'RISK_SUMMARY' ? 'var(--brand-primary-soft)' : 'var(--bg-surface)'
            }}
            onClick={() => setReportType('RISK_SUMMARY')}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.35rem' }}>
              <FileText size={18} color="var(--brand-primary-light)" />
              <strong style={{ fontSize: '0.95rem' }}>Student Risk Summary & Trigger Log</strong>
            </div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0 }}>
              Lists all HIGH and MEDIUM risk students with composite scores, sub-score breakdown, and detected reasons.
            </p>
          </div>

          <div
            className="ef-card"
            style={{
              cursor: 'pointer',
              borderColor: reportType === 'ATTENDANCE_VULNERABILITY' ? 'var(--brand-primary-light)' : 'var(--border-subtle)',
              background: reportType === 'ATTENDANCE_VULNERABILITY' ? 'var(--brand-primary-soft)' : 'var(--bg-surface)'
            }}
            onClick={() => setReportType('ATTENDANCE_VULNERABILITY')}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.35rem' }}>
              <Calendar size={18} color="var(--brand-primary-light)" />
              <strong style={{ fontSize: '0.95rem' }}>Attendance Trajectory & Absence Warnings</strong>
            </div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0 }}>
              Highlights students falling below the 75% statutory attendance threshold across recent 14-day data windows.
            </p>
          </div>

          <div
            className="ef-card"
            style={{
              cursor: 'pointer',
              borderColor: reportType === 'ACADEMIC_DECLINE' ? 'var(--brand-primary-light)' : 'var(--border-subtle)',
              background: reportType === 'ACADEMIC_DECLINE' ? 'var(--brand-primary-soft)' : 'var(--bg-surface)'
            }}
            onClick={() => setReportType('ACADEMIC_DECLINE')}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.35rem' }}>
              <FileSpreadsheet size={18} color="var(--brand-primary-light)" />
              <strong style={{ fontSize: '0.95rem' }}>Term-over-Term Academic Decline Audit</strong>
            </div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0 }}>
              Subject-wise marks comparison between Term 1 and Term 2 to identify sudden drops.
            </p>
          </div>
        </div>
      </div>

      {/* Report Preview Modal */}
      {showPreviewModal && (
        <div
          style={{
            position: 'fixed',
            top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(0, 0, 0, 0.65)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 99999,
            padding: '1.5rem'
          }}
          onClick={() => setShowPreviewModal(false)}
        >
          <div
            className="ef-card animate-fade"
            style={{
              width: '100%',
              maxWidth: '750px',
              maxHeight: '85vh',
              background: 'var(--bg-surface)',
              display: 'flex',
              flexDirection: 'column',
              padding: '2rem',
              overflow: 'hidden'
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '1rem', marginBottom: '1rem' }}>
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <ShieldCheck size={22} color="var(--brand-primary-light)" />
                  <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--text-primary)', margin: 0 }}>
                    EarlyFlag Official Academic Risk Audit
                  </h3>
                </div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
                  Generated on {new Date().toLocaleDateString()} • Mentor: {teacher?.name} ({teacher?.id})
                </div>
              </div>

              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button className="btn btn-secondary btn-sm" onClick={handlePrint} style={{ gap: '0.35rem' }}>
                  <Printer size={14} />
                  <span>Print</span>
                </button>
                <button className="btn btn-primary btn-sm" onClick={handleDownloadReport} style={{ gap: '0.35rem' }}>
                  <Download size={14} />
                  <span>Download</span>
                </button>
              </div>
            </div>

            {/* Scrollable Report Content */}
            <div style={{ flex: 1, overflowY: 'auto', paddingRight: '0.5rem', fontSize: '0.84rem' }}>
              <div style={{ background: 'var(--bg-subtle)', padding: '1rem', borderRadius: 'var(--radius-md)', marginBottom: '1rem' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem', textAlign: 'center' }}>
                  <div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Total Students</div>
                    <div style={{ fontSize: '1.2rem', fontWeight: 800 }}>{students.length}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--risk-high-text)' }}>High Risk</div>
                    <div style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--risk-high-text)' }}>
                      {students.filter(s => s.riskLevel === 'HIGH').length}
                    </div>
                  </div>
                  <div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--risk-med-text)' }}>Medium Risk</div>
                    <div style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--risk-med-text)' }}>
                      {students.filter(s => s.riskLevel === 'MEDIUM').length}
                    </div>
                  </div>
                </div>
              </div>

              <table className="ef-table">
                <thead>
                  <tr>
                    <th>Student Name</th>
                    <th>ID</th>
                    <th>Class</th>
                    <th>Risk Score</th>
                    <th>Level</th>
                    <th>Primary Triggers</th>
                  </tr>
                </thead>
                <tbody>
                  {students.slice(0, 8).map(s => (
                    <tr key={s.id}>
                      <td style={{ fontWeight: 600 }}>{s.name}</td>
                      <td><code>{s.studentId}</code></td>
                      <td>{s.class}-{s.section}</td>
                      <td style={{ fontWeight: 700 }}>{s.riskScore}/100</td>
                      <td>{s.riskLevel}</td>
                      <td style={{ fontSize: '0.75rem' }}>{s.reasonCodes.join(', ') || 'Stable performance'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '1rem', borderTop: '1px solid var(--border-subtle)', paddingTop: '0.75rem' }}>
              <button className="btn btn-secondary btn-sm" onClick={() => setShowPreviewModal(false)}>
                Close Preview
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
